//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swinny_VET_Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public System.DateTime TREATMENTDATE { get; set; }
        public string NOTES { get; set; }
        public Nullable<int> PRICE { get; set; }
        public string PETTYPE { get; set; }
        public string PETNAME { get; set; }
        public int OWNERID { get; set; }
        public int PROCEDUREID { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual Procedure Procedure { get; set; }
    }
}
