CREATE TABLE [dbo].[Treatment]
(
	[TREATMENTDATE] DATE,
	[NOTES] NVARCHAR(100),
	[PRICE] INT, 
	[PETTYPE] NVARCHAR(20),
	[PETNAME] NVARCHAR(20), 
	[OWNERID] INT,
	[PROCEDUREID] INT,

	PRIMARY KEY(TREATMENTDATE, PETTYPE, PETNAME, OWNERID, PROCEDUREID),

	FOREIGN KEY(PETTYPE, PETNAME, OWNERID) REFERENCES [dbo].[Pet],
	FOREIGN KEY(PROCEDUREID) REFERENCES [dbo].[Procedure]
)
